
-- DROP TABLE IF ALREADY EXISTS --
DROP TABLE IF EXISTS BRF_CON_INST;

----- CREATE ROW TABLEs -----

CREATE TABLE BRF_CON_INST (
ID  BIGINT not null primary key,
INST_TYPE SMALLINT not null,
NAME VARCHAR(130) not null,
DESCRIPTION VARCHAR(255) not null,
DATASET VARCHAR(50) not null,
START_DATE DATE,
VALID_RNG_START TIMESTAMP,
VALID_RNG_END TIMESTAMP,
TRANS_RNG_START TIMESTAMP not null,
TRANS_RNG_END TIMESTAMP not null
) USING row OPTIONS() ;


CREATE TABLE BRF_IR (
INST_ID  BIGINT not null primary key,
CURRENCY VARCHAR(3) not null,
PAY_FREQ  SMALLINT not null,
VALID_RNG_START TIMESTAMP,
VALID_RNG_END TIMESTAMP,
TRANS_RNG_START TIMESTAMP ,
TRANS_RNG_END TIMESTAMP,
CONSTRAINT fk_id FOREIGN KEY (INST_ID) REFERENCES BRF_CON_INST(ID)
) USING row OPTIONS() ;


CREATE TABLE BRF_IR_NODE (
INST_ID  INTEGER not null ,
NODE_ID SMALLINT not null,
MATURITY  VARCHAR(10) ,
VALID_RNG_START TIMESTAMP,
VALID_RNG_END TIMESTAMP,
TRANS_RNG_START TIMESTAMP  not null,
TRANS_RNG_END TIMESTAMP  not null,
CONSTRAINT fk_inst_id FOREIGN KEY (INST_ID) REFERENCES BRF_IR(INST_ID)
) USING row OPTIONS() ;

CREATE TABLE BRF_VAL_TYPE (
VAL_TYPE SMALLINT not null,
DESCRIPTION  VARCHAR(60) ,
) USING row OPTIONS() ;


CREATE TABLE BTS_IR_OBS_CORRECTION (
NODE_ID  INTEGER ,
OBS_DATE TIMESTAMP,
VAL_TYPE  SMALLINT ,
VAL NUMERIC(24, 12),
TRANS_RNG_START TIMESTAMP  not null,
TRANS_RNG_END TIMESTAMP  not null,
CORRECTION_DATE TIMESTAMP not null,
CONSTRAINT fk1_node_id FOREIGN KEY (NODE_ID) REFERENCES BRF_IR_NODE(NODE_ID)
) USING row OPTIONS() ;


CREATE TABLE INST_NAME_CORRECTION (
INST_ID  BIGINT not null ,
OLD_NAME VARCHAR(130) not null,
LATEST_NAME VARCHAR(130) not null,
NAME_CHANGE_DATE TIMESTAMP not null
) USING row OPTIONS() ;



-------------------- CREATE COLUMN TABLEs------------


CREATE TABLE BTS_IR_OBS (
NODE_ID  INTEGER ,
OBS_DATE TIMESTAMP,
VAL_TYPE  SMALLINT ,
VAL NUMERIC(24, 12),
TRANS_RNG_START TIMESTAMP  not null,
TRANS_RNG_END TIMESTAMP  not null,
CONSTRAINT fk_node_id FOREIGN KEY (NODE_ID) REFERENCES BRF_IR_NODE(NODE_ID)
) USING column OPTIONS() ;
